name: 'PR Title Checker'

on: 
  pull_request:
    branches: []
    types: [edited, opened, synchronize, reopened]

jobs:
  PR-title-check:
    runs-on: ubuntu-latest
    steps:
      - uses: naveenk1223/action-pr-title@v1.0.0
        with:
          regex: '^((f(eat|ix)|bug)|docs)/INAPP\-[1-9].+' # Regex the title should match.
          allowed_prefixes: 'feat,fix,bug,docs' # title should start with the given prefix
          prefix_case_sensitive: true # title prefix are case insensitive
          min_length: 10 # Min length of the title
          max_length: 40 # Max length of the title
