name: PR-title-check

on:
  pull_request:
    types: [ opened, reopened,edited,synchronize]
    branches: [ main ]

jobs:
  PR-titel-check:
      uses: bojancakar/pr-title-template/.github/workflow/pr-title.yml@main
