
name: Conventional Commits

on:
  pull_request:
    types: [opened, reopened]
    branches: [main]

jobs:
  build:
    name: Conventional Commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: check 
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: gentleseal/action-conventional-commits@v1.2.1
        with:
          valid-commit-types: >
            [
              "feat:",
              "fix:",
              "docs:"
              ]

