
name: Conventional Commits

on:
  pull_request:

jobs:
  build:
    name: Conventional Commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: gentleseal/action-conventional-commits@v1.2.1
        with:
          valid-commit-types: >
            [
              "feat:",
              "fix:",
              "docs:",
            ]
