name: CI 

on:
  workflow_call:
    inputs:
      event_name:
        type: string
        required: true

jobs:
  PR-title-check:
    if: inputs.event_name == 'opened' 
    uses: bojancakar/kk/.github/workflows/pr-title-check.yml@main

  # PR-label-check-and-reminder-comment:
  #   if: github.event.pull_request.opened == true || 
  #   uses: bojancakar/kk/.github/workflows/label-check&reminder-comment.yml@main
  #   secrets:
  #     repo_token: ${{ secrets.GITHUB_TOKEN }}
  
  # Docker-build-test:
  #   needs: [PR-title-check, PR-label-check-and-reminder-comment]
  #   if: github.event.name == "push"
  #   uses: bojancakar/kk/.github/workflows/docker-build.yml@main
  #   secrets:
  #     service_name: ${{secrets.SERVICE_NAME}}

