name: CI 

on:
  workflow_call:
    inputs:
      event_name:
        type: string
        required: true

jobs:
  PR-title-check:
    uses: bojancakar/test-templates/.github/workflows/pr-title-check.yml@main
  
  Docker-build-test:
    uses: bojancakar/test-templates/.github/workflows/docker-build.yml@main
    secrets:
      service_name: ${{secrets.SERVICE_NAME}}


