on:
  workflow_call:


jobs:

  add-label:
    if: github.event.pull_request.opened == true
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Add label to pull request
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            -d "{\"labels\":[\"no_release\"]}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/labels"


  check_label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check label
        run: |
          labels=$(jq --raw-output '.pull_request.labels[] | .name' "$GITHUB_EVENT_PATH")

          if [[ $labels =~ ^(no_release|version:minor|version:major|version:patch)$ ]]; then
            echo "Exactly one label is selected."
          else
            echo "Error: You need to select exactly one label."
            exit 1
          fi
          

  reminder_comment:
    needs: check_label
    if: failure()
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Comment on pull request
      run: |
        curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -X POST -d '{"body": "This is a comment on the pull request"}'\
        https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/comments
