on:
  workflow_call:


jobs:

  add-label:
    if: github.event.pull_request.opened == true
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Add label to pull request
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            -d "{\"labels\":[\"no_release\"]}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/labels"

  check_labels:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check labels
      if: ((contains(toJson(github.event.pull_request.labels.*.name), 'no_release') || contains(toJson(github.event.pull_request.labels.*.name), 'version:patch') || contains(toJson(github.event.pull_request.labels.*.name), 'version:minor') || contains(toJson(github.event.pull_request.labels.*.name), 'version:major')) && (length(github.event.pull_request.labels) == 1))
      run: exit 0
    - name: Fail if invalid label
      if: failure()
      run: exit 1

  reminder_comment:
    needs: Looking_for_labels
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: ':bangbang: This is github action reminder. :bangbang: When you make a PR on the main branch, you have to choose exactly one label.'
