on:
  workflow_call:


jobs:

  add-label:
    if: github.event.pull_request.opened == true
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Add label to pull request
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            -d "{\"labels\":[\"no_release\"]}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/labels"


  check_label:
    runs-on: ubuntu-latest
    name: Check label
    steps:
      - uses: actions/checkout@v2
      - name: Check labels
        run: |
          labels=$(curl -s https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/labels | jq '.[].name')

          valid_label_found=false

          if [[ $labels == *"no_release"* ]]; then
            valid_label_found=true
          elif [[ $labels == *"version:patch"* ]]; then
            valid_label_found=true
          elif [[ $labels == *"version:minor"* ]]; then
            valid_label_found=true
          elif [[ $labels == *"version:major"* ]]; then
            valid_label_found=true
          fi

          if $valid_label_found && [[ $labels == *" "* ]]; then
            exit 1
          elif $valid_label_found; then
            exit 0
          else
            exit 1
          fi


  reminder_comment:
    needs: check_label
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: ':bangbang: This is github action reminder. :bangbang: When you make a PR on the main branch, you have to choose exactly one label.'
# ${{contains(github.event.pull_request.labels.*.name, 'version:minor')}}