on:
  workflow_call:


jobs:

  add-label:
    if: github.event.pull_request.opened == true
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Add label to pull request
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            -d "{\"labels\":[\"no_release\"]}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/labels"


  check_label:
    runs-on: ubuntu-latest
    name: Check label
    steps:
      - uses: actions/checkout@v2
      - name: Check labels
        run: if ! grep -qE 'no_release|version:patch|version:minor|version:major' <<< "$GITHUB_EVENT_PATH"; then
            echo "Pull request nije označen sa nekom od navedenih labela"
            exit 1
          fi

          echo "Pull request je označen sa nekom od navedenih labela"
            exit 0


  reminder_comment:
    needs: check_label
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: ':bangbang: This is github action reminder. :bangbang: When you make a PR on the main branch, you have to choose exactly one label.'
# ${{contains(github.event.pull_request.labels.*.name, 'version:minor')}}