on:
  workflow_call:


jobs:

  add-label:
    if: github.event.pull_request.opened == true
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Add label to pull request
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            -d "{\"labels\":[\"no_release\"]}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/labels"

  check_label:
    runs-on: ubuntu-latest
    name: Check label
    steps:
      - uses: actions/checkout@v2
      - name: Check labels
        run: |
          # Get labels on the pull request
          labels=$(curl -s https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/labels | jq '.[].name')

          # Initialize flag to false
          valid_label_found=false

          # Check if exactly one of the desired labels is present
          if [[ $labels == *"no_release"* ]] || [[ $labels == *"version:major"* ]] || [[ $labels == *"version:minor"* ]] || [[ $labels == *"version:patch"*]]; then
            # Valid label found
            valid_label_found=true
          fi

          # Check if exactly one valid label was found and if there is only one label present
          if $valid_label_found && [[ $labels == *" "* ]]; then
            # Multiple labels present
            echo "Vise labela"
            exit 1
          elif $valid_label_found; then
            # Exactly one valid label was found
            echo "bravo tacno jedna labela"
            exit 0
          else
            # No valid label found or multiple valid labels found
            echo "Vise labela ili nijedna"
            exit 1
          fi
          
  reminder_comment:
    needs: check_label
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: ':bangbang: This is github action reminder. :bangbang: When you make a PR on the main branch, you have to choose exactly one label.'
# ${{contains(github.event.pull_request.labels.*.name, 'version:minor')}}