on:
  workflow_call:


jobs:

  add-label:
    if: github.event.pull_request.opened == true
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Add label to pull request
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            -d "{\"labels\":[\"no_release\"]}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/labels"

  check_label:
    runs-on: ubuntu-latest
    name: Check label
    steps:
      - uses: actions/checkout@v2
      - name: Check labels
        run: |
          # Lable koje treba proveriti
          VALID_LABELS=("no_release" "version:patch" "version:minor" "version:major")
          
          # Proveri da li je postavljena tačno jedna od ovih labli
          LABEL_COUNT=0
          for LABEL in "${VALID_LABELS[@]}"; do
            RESULT=$(git ls-remote --refs --tags origin "refs/heads/$LABEL" 2>/dev/null)
            if [[ -n "$RESULT" ]]; then
              LABEL_COUNT=$((LABEL_COUNT + 1))
            fi
          done
          
          # Ako nije postavljena ni jedna labla ili ako je postavljeno više od jedne labele, onda ispiši poruku o grešci
          if [[ "$LABEL_COUNT" -ne 1 ]]; then
            echo "Error: No label found or more than one label found."
            exit 1
          fi
          
          # Ako je tačno jedna labla postavljena, onda workflow prolazi
          exit 0

  reminder_comment:
    needs: check_label
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: ':bangbang: This is github action reminder. :bangbang: When you make a PR on the main branch, you have to choose exactly one label.'
# ${{contains(github.event.pull_request.labels.*.name, 'version:minor')}}