on:
  workflow_call:


jobs:

  add-label:
    if: github.event.pull_request.opened == true
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Add label to pull request
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            -d "{\"labels\":[\"no_release\"]}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/labels"


  check_label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check label
        if: contains(github.event.pull_request.labels.*.name, 'no_release') || contains(github.event.pull_request.labels.*.name, 'version:minor') || contains(github.event.pull_request.labels.*.name, 'version:major') || contains(github.event.pull_request.labels.*.name, 'version:patch')
        run: |
          if github.event.pull_request.labels.total_count == 1
          then
            echo "Label is present. Pipeline will continue."
            exit 0 
          else
            echo "Invalid number of labels. Pipeline will be terminated."
            exit 1
          

  reminder_comment:
    needs: check_label
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: ':bangbang: This is github action reminder. :bangbang: When you make a PR on the main branch, you have to choose exactly one label.'
# ${{contains(github.event.pull_request.labels.*.name, 'version:minor')}}