on:
  workflow_call:


jobs:

  add-label:
    if: github.event.pull_request.opened == true
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Add label to pull request
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            -d "{\"labels\":[\"no_release\"]}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/labels"

  check_labels:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check labels
      run: |
        # Get the list of labels for the pull request
        labels=$(curl -s https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/labels | jq '.[].name')

        # Check if exactly one of the desired labels is present
        if [[ $labels == *"no_release"* ]]; then
          # Valid label found
          exit 0
        elif [[ $labels == *"version:patch"* ]]; then
          # Valid label found
          exit 0
        elif [[ $labels == *"version:minor"* ]]; then
          # Valid label found
          exit 0
        elif [[ $labels == *"version:major"* ]]; then
          # Valid label found
          exit 0
        else
          # No valid label found
          exit 1
        fi

  reminder_comment:
    needs: check_labels
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: ':bangbang: This is github action reminder. :bangbang: When you make a PR on the main branch, you have to choose exactly one label.'
# ${{contains(github.event.pull_request.labels.*.name, 'version:minor')}}