name: Tag

on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v2

      # Get the current version tag
      - name: Get current version
        run: |
          # Get the latest tag
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          # If no tags exist, use "v0" as the initial version
          if [ -z "$latest_tag" ]; then
            latest_tag="v0"
          fi
          # Extract the version number from the tag
          version=${latest_tag:1}
          # Increment the version number
          version=$((version+1))
          # Construct the new tag name
          new_tag="v$version"

      # Tag the repository
      - name: Tag
        run: |
          git tag $new_tag
          git push origin $new_tag